spring:
  application:
    name: meowKanban
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/meowkanban.db
    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
